### ISSUE TITLE
Support class auto import with its type

### ISSUE THREAD

**Issue by otomad** [unplugin/unplugin-auto-import#439]
### Clear and concise description of the problem

If declare and export a class.

```typescript
export default class Foo {

}
```

While directly use it for construct a new instance. Yeah it works properly.
```typescript
const foo = new Foo();
```

However if use this class for type hint, TypeScript will not recognize it.
```typescript
const foo: Foo = new Foo();
           ^^^

function myFunc(foo: Foo) {
                     ^^^
}
```

> Error: 'Foo' refers to a value, but is being used as a type here. Did you mean 'typeof Foo'?

`typeof Foo` will be the type of Foo's constructor, that is `new () => Foo`, like StringConstructor of String;

You have to import that class explicitly, then it will work.

```typescript
import type Foo from "../classes/Foo";
```

### Suggested solution

Do not use `typeof import(xxx)` in the auto-imports.d.ts, use `export xxx from` instead. Just like it in latest Nuxt auto import method.

```typescript
const Foo: typeof import('../classes/Foo')['default'];
```

change to

```typescript
export Foo from '../classes/Foo';
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ZiFy** [comment]
我也遇到了相同的问题，现在有解决方案吗？
I ran into the same problem, is there a solution now?

**Comment by hf-xz** [comment]
My solution using `InstanceType`:
```ts
// Api.ts
export class Api {
  ...
}

// auto-imports.d.ts
declare global {
  ...
  const Api: typeof import('./src/apis/Api')['Api']
}

// other file
let someApi: InstanceType<typeof Api> = new Api()

// or
type ApiType = InstanceType<typeof Api>
let someApi: ApiType = new Api()
function myFunc(api: ApiType) {
  ...
}
```

**Comment by tohere** [comment]
我也有这个问题, 当我使用导入 threejs 中的部分类的时候会报这个错, 如果不加 type, 那就是导入的类, 如果加上 type, 那就是导入的类型, 希望能有个参数控制两者都能使用
```typescript
 AutoImport({
	imports: [
		{
	      from: 'three',
	      imports: ['Group'],
		 // type: true
	    }
	]
} )
```

**Comment by senritsu** [comment]
Same here for `three`, it works to auto-import either as types or values, but not both.

**Comment by otomad** [comment]
如果在自动导入的 .d.ts 文件中使用以下声明即可同时导入变量及其类型。
If this declaration is used in the auto import .d.ts file, variables and types can be imported at the same time.

```typescript
import _0 from "classes/Foo";
import _1 from "classes/Bar"
import _2 from "classes/Baz"

declare global {
    export { default as Foo, Foo1, Foo2 } from "classes/Foo";
    export { default as Bar, Bar1, Bar2 } from "classes/Bar";
    export { default as Baz, Baz1, Baz2 } from "classes/Baz";
}
```

其中，Foo 是默认导出，Foo1、Foo2 是命名导出，其它同理。
顶部导入语句中的变量名称随意，此处使用下划线加数字表示，因为名称并不重要。但是不能不写，如果不写，则下方导出的变量类型全部都是 any。并且导入和导出语句需要都写一遍路径。
Foo is the default export, Foo1 and Foo2 are named exports, same to others.
Feel free to name the variables from the top import statements, which are represented by underscore with numbers here, because the names are unimportant. But it cannot be removed, otherwise all exported variable types will be "any". So both import and export statements require to type the path.

此外，如果你使用了 Nuxt，则只能使用命名导出而不能使用默认导出，这是因为 Nuxt 的自动导入功能对默认导出使用文件名而非变量名命名。糟糕的是，Nuxt 将文件名进行了小驼峰化处理，这导致了作为一个类却使用了小驼峰的名字，看起来非常不适宜。
In addition, if you are using Nuxt, you can only use named exports and cannot use default exports because Nuxt's auto import feature names default exports with the filename instead of the variable name. Unfortunately, Nuxt has camelized the file name, which result in the class using a camel name, looks very inappropriate.

**Comment by ilyaliao** [comment]
It seems that the issue has been resolved in the new version.

**Comment by Anoesj** [comment]
> It seems that the issue has been resolved in the new version.

The problem persists for me. What changes have you noticed exactly?

**Comment by ilyaliao** [comment]
> What I did notice is that, if that if you do `type: true` on all your class imports, the types are in fact exported too. However, I don't think they're exported in the most convenient way. I ran into weird TypeScript issues [like this](https://github.com/microsoft/TypeScript/issues/6307) everywhere I used the "type version" of a class (so the type of the class instance, like `type TheClassInstanceArray = TheClass[]`).

Sorry, I didn't notice this was a default export. The upstream currently doesn't support this behavior.

**Comment by Anoesj** [comment]
Ah I see. I'm not OP, my case was only different in that it's happening with named exports too in my projects. I don't think it's limited to default exports. I'll see if I can create a repro for my cases soon.

**Comment by ilyaliao** [comment]
Looks like this is already fixed. Closing this one!
